#!/bin/bash

curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
heroku login
pip install gunicorn
#a list of Python libraries installed so far
pip freeze > requirements.txt
#a file to tell Heroku to run flask using Gunicorn
touch Procfile
echo web: gunicorn routes:app> Procfile
#create new heroku app(new subdomain for the app)
#create Git remote repository on the Heroku servers
heroku create
git add Procfile
git add requirements.txt
git commit -m "Heroku config"
git push heroku master


